// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDu4eNO3z9RGHGw-0B1DjyI8NKXYN8gbxk',
    appId: '1:56987270260:web:70e684c14e3d6662d2e521',
    messagingSenderId: '56987270260',
    projectId: 'herfati-app',
    authDomain: 'herfati-app.firebaseapp.com',
    storageBucket: 'herfati-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrpwySDAQ8JB7uLIlXPpaHoXHCPFIpEwc',
    appId: '1:56987270260:android:06b3e8a65a49ae44d2e521',
    messagingSenderId: '56987270260',
    projectId: 'herfati-app',
    storageBucket: 'herfati-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmJRdBGuch8bJyMPRPJJHFH8MeTAR2Vjw',
    appId: '1:56987270260:ios:17a7d1cdaaa09e2ed2e521',
    messagingSenderId: '56987270260',
    projectId: 'herfati-app',
    storageBucket: 'herfati-app.firebasestorage.app',
    iosBundleId: 'com.example.herfatiapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmJRdBGuch8bJyMPRPJJHFH8MeTAR2Vjw',
    appId: '1:56987270260:ios:17a7d1cdaaa09e2ed2e521',
    messagingSenderId: '56987270260',
    projectId: 'herfati-app',
    storageBucket: 'herfati-app.firebasestorage.app',
    iosBundleId: 'com.example.herfatiapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDu4eNO3z9RGHGw-0B1DjyI8NKXYN8gbxk',
    appId: '1:56987270260:web:0df7b092cedd7c8ed2e521',
    messagingSenderId: '56987270260',
    projectId: 'herfati-app',
    authDomain: 'herfati-app.firebaseapp.com',
    storageBucket: 'herfati-app.firebasestorage.app',
  );

}