// This file is generated by FlutterFire CLI
// It contains Firebase configuration for all platforms

// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// This class contains Firebase settings for each platform
/// (Android, iOS, Web, Windows, Mac)
class DefaultFirebaseOptions {
  /// This getter returns the correct Firebase configuration
  /// depending on the platform where the app is running
  static FirebaseOptions get currentPlatform {
    // If the app is running on Web (browser)
    if (kIsWeb) {
      return web;
    }

    // Check the platform type (Android, iOS, etc.)
    switch (defaultTargetPlatform) {
      // Android device
      case TargetPlatform.android:
        return android;

      // iPhone / iPad
      case TargetPlatform.iOS:
        return ios;

      // Mac computer
      case TargetPlatform.macOS:
        return macos;

      // Windows computer
      case TargetPlatform.windows:
        return windows;

      // Linux is not supported in this setup
      case TargetPlatform.linux:
        throw UnsupportedError(
          'Firebase is not configured for Linux. '
          'Run FlutterFire CLI to add support.',
        );

      // Any other unknown platform
      default:
        throw UnsupportedError(
          'This platform is not supported by Firebase configuration.',
        );
    }
  }

  /// Firebase configuration for WEB
  static const FirebaseOptions web = FirebaseOptions(
    // API key used to connect to Firebase project
    apiKey: 'AIzaSyDu4eNO3z9RGHGw-0B1DjyI8NKXYN8gbxk',

    // Unique app ID for web app
    appId: '1:56987270260:web:70e684c14e3d6662d2e521',

    // Sender ID used for notifications
    messagingSenderId: '56987270260',

    // Firebase project ID
    projectId: 'herfati-app',

    // Domain for authentication
    authDomain: 'herfati-app.firebaseapp.com',

    // Storage bucket for files (images, videos, etc.)
    storageBucket: 'herfati-app.firebasestorage.app',
  );

  /// Firebase configuration for ANDROID
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrpwySDAQ8JB7uLIlXPpaHoXHCPFIpEwc',
    appId: '1:56987270260:android:06b3e8a65a49ae44d2e521',
    messagingSenderId: '56987270260',
    projectId: 'herfati-app',
    storageBucket: 'herfati-app.firebasestorage.app',
  );

  /// Firebase configuration for iOS (iPhone / iPad)
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmJRdBGuch8bJyMPRPJJHFH8MeTAR2Vjw',
    appId: '1:56987270260:ios:17a7d1cdaaa09e2ed2e521',
    messagingSenderId: '56987270260',
    projectId: 'herfati-app',
    storageBucket: 'herfati-app.firebasestorage.app',

    // Unique identifier for iOS app
    iosBundleId: 'com.example.herfatiapp',
  );

  /// Firebase configuration for MacOS
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmJRdBGuch8bJyMPRPJJHFH8MeTAR2Vjw',
    appId: '1:56987270260:ios:17a7d1cdaaa09e2ed2e521',
    messagingSenderId: '56987270260',
    projectId: 'herfati-app',
    storageBucket: 'herfati-app.firebasestorage.app',
    iosBundleId: 'com.example.herfatiapp',
  );

  /// Firebase configuration for Windows
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDu4eNO3z9RGHGw-0B1DjyI8NKXYN8gbxk',
    appId: '1:56987270260:web:0df7b092cedd7c8ed2e521',
    messagingSenderId: '56987270260',
    projectId: 'herfati-app',
    authDomain: 'herfati-app.firebaseapp.com',
    storageBucket: 'herfati-app.firebasestorage.app',
  );
}
